class Turret:
    name = None
    flavor = None
    hp = None
    shield = None
    maxHeat = None
    coolingRate = None
    coolingDelay = None
    weapons = None
    unlock = None
    stats = None
    mechanics = None
    openSlots = 1
    
    def __init__(self, name, flavor, health, shield, maxHeat, coolingRate, coolingDelay, weapons, unlock, stats, mechanics, openSlots = 1):
        self.name = str(name)
        self.flavor = str(flavor)
        self.hp = str(health) if health > 0 else "#X"
        self.sp = str(shield) if shield > 0 else "#X"
        self.maxHeat = str(maxHeat)
        self.coolingRate = str(coolingRate)
        self.coolingDelay = str(coolingDelay)
        self.weapons = weapons
        self.unlock = unlock
        self.stats = stats
        self.mechanics = mechanics
        self.openSlots = openSlots
        
turrets = [
    #      Name         Flavor Text                                   HP  SP  MH    CR         CD       Weapon/Mod Slots                  Unlock Requirements                                                                                                                       Other Stats                                                                                                              Special Mechanics
    #      ----         -----------                                   --  --  --    --         --       ----------------                  -------------------                                                                                                                       -----------                                                                                                              -----------------
    Turret("Demon",     "you've made a deal with the devil.",         1,  0,  100,  "100/s",   "1s",    [(4, 4), (4, 4), (4, 4)],         "Eliminate #B6666$\n$Microbes$.",                                                                                                    [],                                                                                                                           ["First hit per $Microbe$ can $Burn$ (20% chance).", "Will always die when damaged."]),
    Turret("Maw",       "swallow them whole.",                        60, 0,  50,   "50/s",    "1s",    [(4, 3)],                         "Read every $Microbe$ description.",                                                                                                 ["$Damage -70%$", "$TurretScale +100%$"],                                                                                     ["Eat $Microbes$ to gain $Health$.", "Every 2s, -1 $Health$."]),
    Turret("Scorch",    "keep your cool.",                            40, 0,  50,   "50/s",    "1s",    [(4, 3), (4, 3), (4, 3)],         "Achieve victory in any mode #B10$ times.",                                                                                          [],                                                                                                                           ["$Firerate$ increases up to +300% with $Heat$.", "Destroyed when\n$HeatMax$ reached."]),
    Turret("Helios",    "rise & radiate.",                            80, 0,  100,  "25/s",    "0.75s", [(4, 3), (3, 3), (2, 3), (1, 3)], "Achieve victory in #BBrood$ mode #B10$ times.",                                                                                     ["$Accuracy: 360°$", "$TurretScale +200%$"],                                                                                  ["Cannot be aimed.", "Rotates while charging.", "$Charge$ and release to fire.", "$Damage$, $Knockback$, $Size$, and $Speed$ scale with $Charge$."]),
    Turret("Diesel",    "fuel up between waves.",                     45, 0,  150,  "#X",      "#X",    [(4, 3), (4, 3), (4, 3)],         "Reach $HeatMax$ #B500$ times.",                                                                                                     ["$TurretScale +25%$"],                                                                                                       ["While $Fuel < 50%$,\n$Damage +100%$."]),
    Turret("Crane",     "cells are the building blocks of life.",     0,  16, 125,  "25/s",    "2s",    [(3, 2), (3, 2), (3, 2), (3, 2)], "Achieve victory in any mode at $Depth 5$ with a\n$Sticky$ weapon that didn't originally have\n$Sticky.",                            ["$Sticky$", "$Sticky Duration +4s$", "$Bounce$", "$Range -50%$", "$Firerate -50%$", "$Damage -50%$", "$TurretScale +100%$"], []),
    Turret("Colossus",  "large and in charge.",                       80, 0,  125,  "75/s",    "1s",    [(4, 3), (4, 3), (4, 3)],         "Survive wave #B50$ in any mode at $Depth 3 (or deeper)$.",                                                                          ["$Damage +40%$", "$Firerate -40%$", "$Size +40%$", "$Speed -40%$", "$TurretScale +200%$"],                                   []),
    Turret("Commander", "lead your soldier to victory.",              40, 0,  100,  "75/s",    "1s",    [(4, 3), (4, 3), (4, 3)],         "Achieve victory in any mode at $Depth 3 (or deeper)$ with the #BGyroscope$ perk.",                                                  ["$Range +100%$", "$Firerate -50%$", "$Speed -50%$"],                                                                         ["While firing, projectiles home towards crosshair and $Homing +400%$.", "While not firing,\n$Homing +2000%$."]),
    Turret("Surge",     "constantly generates electricity.",          35, 0,  25,   "3.1/s",   "1s",    [(4, 3), (4, 3), (4, 3)],         "Achieve victory in any mode at $Depth 3 (or deeper)$ with both the #BThermometer$ perk and #BExtinguisher$ perk at the same time.", ["$TurretScale -25%$"],                                                                                                       ["While $Electricity = 100%$, $Damage +30%$.", "While $Electricity > 0%$, no $ElectricityD$."]),
    Turret("Saturn",    "all aboard the cosmic carousel.",            70, 0,  100,  "50/s",    "1s",    [(4, 3), (4, 2), (4, 1)],         "Unlock #B20$ perks.",                                                                                                               ["$TurretScale +150%$"],                                                                                                      ["Cannot be aimed.", "Rotates constantly.", "Projectiles orbit the turret.", "$Health$ cannot be reduced by more than 3 when hit."]),
    Turret("Bearclaw",  "good things come in threes.",                45, 0,  100,  "100/s",   "1s",    [(3, 6)],                         "Achieve victory in #BBrood$ mode at $Depth 5$.",                                                                                    ["$Damage -40%$", "$Size -30%$", "$TurretScale +25%$"],                                                                       ["Fires from all 3 barrels at once."]),
    Turret("Chrono",    "make every second count.",                   40, 0,  150,  "100/s",   "0.5s",  [(4, 1), (3, 2), (2, 3), (1, 4)], "Achieve #B30$ awards.",                                                                                                             ["$Firerate +100%$", "$Speed +100%$"],                                                                                        ["Cannot be aimed.", "Rotates while not firing.", "Game speed is cut in half while spinning."]),
    Turret("Quad",      "4 weaker weapons.",                          40, 0,  100,  "100/s",   "1s",    [(3, 3), (3, 3), (3, 3), (3, 3)], "Research for #Research400$.",                                                                                                       [],                                                                                                                           []),
    Turret("Fume",      "harvest & haze.",                            30, 0,  100,  "3.3/s",   "0.33s", [(4, 3), (4, 3), (4, 3)],         "Eliminate #B20000$\n$Microbes$.",                                                                                                   ["$Damage -40%$"],                                                                                                            ["$Damage$ spreads to\n$Microbes$ within $Range$ (0-60%, scales with\n$Gas$).", "Getting hit by $Offspring$ increases $Gas$.", "Cannot be damaged by $Offspring$."]),
    Turret("Tank",      "stop to shoot, move to cool.",               40, 4,  100,  "15/s",    "0.5s",  [(4, 4), (3, 3), (2, 2)],         "Achieve victory in #BAbyss$ mode at $Depth 3$.",                                                                                    ["$Movespeed: 15$", "$Damage +100%$", "$Size +60%$", "$Speed +60%$", "$Firerate -60%$", "$TurretScale +50%$"],                ["Cannot shoot while moving.", "Decreases heat while moving."]),
    Turret("Gauss",     "cutting-edge technology.",                   40, 0,  100,  "75/s",    "0.25s", [(4, 5)],                         "Complete a #BDaily Dive$.",                                                                                                         ["$Accuracy +50%$"],                                                                                                          ["$Charge$ and release to fire.", "$Damage$, $Knockback$, and $Speed$ scale with\n$Charge$.", "$Size$ scales with\n$Charge$ if $Hitscan$."]),
    Turret("Dice",      "excellent build control and dependability.", 30, 0,  75,   "75/s",    "1s",    [(4, 3), (4, 3), (4, 3)],         "Achieve victory in #BExtract$ mode.\n#BOR$\nSurvive wave #B20$ in the demo.",                                                       [],                                                                                                                           ["$Reroll$ +1$ on wave end."], openSlots=2),
    Turret("Viper",     "the GALACTIC Guardian!",                     8,  4,  75,   "25/s",    "0.5s",  [(4, 3), (3, 3), (2, 3), (1, 3)], "Achieve victory in #BShmup$ mode at $Depth 5$.",                                                                                    ["$Movespeed: 30$"],                                                                                                          ["$Health$ cannot be reduced by more than 2 when hit.",
                                                                                                                                                                                                                                                                                                                                                                                                                "Mount 1:\nFires forward,\n$Accuracy: pinpoint$,\n$Firerate$ +200%,\n$Speed$ +100%,\n$Damage$ -75%,\n$Knockback -100%$,\n$Size$ -50%.",
                                                                                                                                                                                                                                                                                                                                                                                                                "Mount 2:\nFires at a 45° angle in both directions,\n$Projectiles$ +200%,\n$Speed$ +50%,\n$Size$ +25%,\n$Accuracy$ -100%,\n$Damage$ -75%,\n$Knockback$ -75%.",
                                                                                                                                                                                                                                                                                                                                                                                                                "Mount 3:\nFires at a 90° angle in both directions,\n$Homing$,\n$Accuracy$ +50%,\n$Damage$ +125%,\n$Range$ +100%,\n$Size$ +50%,\n$Firerate$ -66.7%,\n$Speed$ -50%.",
                                                                                                                                                                                                                                                                                                                                                                                                                "Mount 4:\nFires backward,\n$Pierce$,\n$Firerate$ +300%,\n$Knockback$ +150%,\n$Accuracy$ -50%,\n$Damage$ -62.5%,\n$Range -50%,\n$Size -25%."]),
    Turret("Superstar", "dazzle the depths with rainbow light.",      20, 0,  100,  "100/s",   "1s",    [(4, 3), (4, 3), (4, 3)],         "Trigger #B300$ power-ups.",                                                                                                         ["$Power-upChance x5$", "$Damage -20%$"],                                                                                     []),
    Turret("Ramjet",    "rocket-powered recoil!",                     30, 0,  50,   "25/s",    "0.25s", [(4, 5)],                         "Complete #B10$ #BTurret Trials$.",                                                                                                  ["$Knockback +100%$", "$Firerate +100%$", "$Speed +100%$", "$TurretScale -25%$"],                                             ["Firing pushes you back based on $Knockback$.", "$Damage$ -50% on weapons without\n$Knockback$.", "While $Fuel = 0$,\n$FuelD$ +1100%."]),
    Turret("Swap",      "3 weaker but more upgradeable weapons.",     40, 0,  100,  "100/s",   "1s",    [(3, 4), (3, 4), (3, 4)],         "Achieve victory in any mode at $Depth 3$.",                                                                                         [],                                                                                                                           []),
    Turret("Tempest",   "gale force winds.",                          30, 0,  75,   "50/s",    "1s",    [(4, 3), (4, 3), (4, 3)],         "Unlock #B60$ perks.",                                                                                                               ["$Knockback -50%$"],                                                                                                         ["$Knockback$ is applied to all $Microbes$ and\n$Offspring$ with\n$Health > 0$."]),
    Turret("Satellite", "attacks from low orbit.",                    30, 0,  100,  "100/s",   "1s",    [(4, 3), (4, 3), (4, 3)],         "Synthesize every weapon at least once",                                                                                             ["$Damage -99%$"],                                                                                                            ["Elimintate 3 random\n$Microbes$ every 5s."]),
    Turret("Boomerang", "return to sender.",                          40, 0,  100,  "100/s",   "1s",    [(4, 2), (4, 2), (4, 2)],         "Achieve victory in any mode at $Depth 1 (or deeper)$ with a $Pierce$ weapon that didn't originally have $Pierce$.",                 ["$Pierce$", "$Damage -30%$"],                                                                                                ["Projectiles can hit\n$Microbes$ twice.", "Projectiles start moving towards their origin after reaching their $Range$.", "While seeking, $Homing$ projectiles won't return."]),
    Turret("Guardian",  "the original Genome Guardian.",              40, 0,  100,  "100/s",   "1s",    [(4, 3), (4, 3), (4, 3)],         "Your starting turret.",                                                                                                             [],                                                                                                                           ["$Damage$ +100% to the ghost of #AbyssThe Abyss$."]),
    Turret("Spyglass",  "tracks the closest target.",                 30, 0,  50,   "100/s",   "1s",    [(4, 3), (4, 3), (4, 3)],         "Research for #Research4000$.",                                                                                                      ["$Speed +50%$", "$TurretScale -50%$"],                                                                                       ["Cannot be aimed.", "Always points towards the nearest $Microbe$ or $Offspring$."]),
    Turret("Riptide",   "twiest and turn, the riptide churns.",       30, 0,  100,  "10/elim", "3s",    [(3, 2), (3, 2), (3, 2)],         "Defeat #AbyssThe Abyss$ or the ghost of #AbyssThe Abyss$ in under 1 minute (timer starts when its $Health Bar$ stops descending).", ["$Accuracy: 360°$", "$Movespeed: 30$"],                                                                                      ["Cannot be aimed.", "Rotates constantly, scaling with $Movespeed$.", "$Health$ cannot be reduced by more than 1 when hit.", "When hit by a $Microbe$, eliminate that $Microbe$ and increase $Fuel$ by\n$RipR$ (2x for oversized and 3x for megasized).", "When hit by a microbe, increase $Movespeed$,\n$Firerate$, and $Speed$ by 30%, stacking up to 5 times."]),
    Turret("Focus",     "a single, highly-upgradeable weapon.",       35, 0,  100,  "100/s",   "1s",    [(4, 6)],                         "Research for #Research400$.",                                                                                                       ["$Damage +15%$", "$Firerate +15%$", "$TurretScale -25%$"],                                                                   []),
    Turret("Warp",      "bend space. pick place.",                    20, 0,  50,   "150/s",   "1s",    [(4, 4)],                         "Achieve victory in any mode at $Depth 5$ with #B20$ different perks.",                                                              ["$Range -75%$", "$TurretScale -50%$"],                                                                                       ["Projectiles are fired from your crosshair."]),
    Turret("Deadeye",   "always on target.",                          40, 0,  100,  "100/s",   "0.75s", [(4, 3), (4, 3), (4, 3)],         "Achieve victory in any mode at $Depth 3 (or deeper)$ with any weapon with #ACCpinpoint$.",                                                                                          ["$Accuracy: pinpoint$", "$Range +100%$", "$Speed +200%$", "$Firerate -50%$"],                                                []),
    Turret("Shuriken",  "strike from the shadows.",                   10, 0,  75,   "25/s",    "1s",    [(4, 4), (4, 3), (4, 2)],         "Start #B10$ (or more) runs at $Depth 3 (or deeper)$ in a single session.",                                                                                                          [],                                                                                                                           ["Firing builds $Shade$.", "While not firing, drain $Shade$ to stay in Stealth mode.", "Firing before running out of $Shade$ grants\n$Firerate$ +200% and exits Stealth mode."]),
    Turret("Buckler",   "hiding behind its shields.",                 10, 8,  100,  "100/s",   "1s",    [(4, 3), (4, 3), (4, 3)],         "Achieve victory in any mode at $Depth 1 (or deeper)$ with the #BReactor$ perk.",                                                                                                    ["$TurretScale -25%$"],                                                                                                       ["While $Shield = 0$,\n$Firerate$ +50%."]),
    Turret("Fortress",  "the best offense is a good defense.",        80, 8,  150,  "50/s",    "1.5s",  [(3, 2), (3, 2), (3, 2), (3, 2)], "Achieve victory in any mode at $Depth 5$ with\n$HealthMax >= 160$ or $ShieldMax >= 16$.",                                                                                           ["$Firerate -30%$", "$Range -50%$", "$TurretScale +300%$"],                                                                   ["Cannot be aimed.", "Rotates constantly.", "Fires from all 3 barrels at once."]),
    Turret("Castle",    "strong defence, at a price.",                60, 4,  100,  "100/s",   "1s",    [(4, 2), (4, 2), (4, 2)],         "Research for #Research400$.",                                                                                                                                                       ["$TurretScale +50%$"],                                                                                                       []),
    Turret("Boombox",   "for lovers of the game's soundtrack!",       40, 2,  125,  "100/s",   "1.25s", [(4, 3), (4, 3), (4, 3)],         "Achieve victory in #BExtract$ mode #B10$ times.",                                                                                                                                   [],                                                                                                                           ["$Knockback$, $Firerate$, $Accuracy$, $Speed$, and $Size$ are affected by the in-game music."]),
    Turret("Breach",    "up close and personal.",                     40, 2,  100,  "75/s",    "1s",    [(4, 3), (4, 3), (4, 3)],         "Achieve victory in any mode at $Depth 3 (or deeper)$ with a weapon that has #ACC360°$.",                                                                                            ["$Projectiles +300%$", "$Firerate -50%$", "$Accuracy -100%$", "$Range -35%$", "$TurretScale +25%$"],                         []),
    Turret("Jester",    None,                                         0,  0,  None, None,      None,    [(4, 3), (4, 3), (4, 3)],         "Achieve victory in any mode with #B10$ different turrets.\n#BOR$\nEnter J-E-S-T-E-R as a sequence of keyboard inputs.\n#BOR$\nIt has a chance randomly be unlocked while playing.", [],                                                                                                                           ["???"]),
    Turret("Ghost",     "it moves, it finally moves!",                20, 0,  50,   "100/s",   "1s",    [(4, 3), (4, 3), (4, 3)],         "Defeat #AbyssThe Abyss.", ["$Movespeed: 30$", "$TurretScale -25%$"],                                                                                    []),
    Turret("Helix",     "true genetic warfare.",                      30, 0,  50,   "50/s",    "0.5s",  [(4, 5)],                         "Achieve victory in #BGameshow$ mode at $Depth 3$.", ["$Damage -33%$"],                                                                                                            ["Fires from both barrels at once with a helix pattern.", "$Damage$ +50% to\n$Microbes$ per weapon DNA letter if said letter is contained by the\n$Microbe$.", "Extinction mutations occur more often."]),
    Turret("Kaleido",   "simplicity fuels collaboration.",            40, 0,  100,  "100/s",   "1s",    [(1, 4), (1, 4), (1, 4), (1, 4)], "Achieve victory in any mode the #B20$ different weapons.", [],                                                                                                                           ["$Firerate$ +15% per #A$.", "$Accuracy$, $Range$, and $Speed$ +30% per #C$.", "$Size$ and $Knockback$ +70% per #G$.", "$Damage$ +15% per #T$."]),
    Turret("Psyker",    "mind over matter.",                          20, 2,  50,   "50/s",    "0.5s",  [(4, 4), (4, 4)],                 "Achieve victory in any mode at $Depth 5$ with a turret that has\n$Movespeed$.", ["$Movespeed: 30$", "$Range +600%$", "$Knockback +100%$", "$Firerate -60%$", "$TurretScale -25%$"],                           ["Cannot be aimed.", "Always points up.", "While $Heat = 100%$,\n$Damage$ +300%."]),
    Turret("Daisy",     "spins, firing through 2 barrels at once.",   40, 0,  100,  "75/s",    "0.75s", [(4, 3), (4, 3), (4, 3)],         "Discover all $Microbes$.", ["$Firerate +30%$"],                                                                                                          ["Cannot be aimed.", "Rotates constantly.", "Fires from both barrels at once."]),
    Turret("Bouncer",   "spring-loaded security",                     40, 0,  100,  "125/s",   "1.25s", [(4, 3), (4, 2), (4, 1)],         "Achieve victory in any mode at $Depth 5$ with a\n$Bounce$ weapon that didn't originally have\n$Bounce$.", ["$Bounce$", "$Range +200%$", "$Knockback +100%$", "$Firerate -60%$"],                                                        ["Projectiles gain\n$Damage$ +100% per\n$Microbe$ bounce (up to $Damage$ +200%)."]),
    Turret("Akimbo",    "dual wields tier 2 weapons.",                40, 0,  100,  "100/s",   "1s",    [(2, 5), (2, 5)],                 "Achieve victory in #BClassic$ mode at $Depth 5$.", ["$Firerate +40%$"],                                                                                                          []),
    Turret("Dragoon",   "echoes of the dragon's roar.",               30, 0,  75,   "125/s",   "1s",    [(4, 4), (4, 4)],                 "Achieve victory in #BClassic$ mode #B10$ times.", ["$CriticalChance +30%$", "$Range +50%$", "$Damage -40%$"],                                                                   ["$CriticalHits$ redirect non-$Hitscan$ projectiles towards the nearest\n$Microbe$.", "$CriticalHits$ add\n$Bounce$ to $Hitscan$ weapons and grant 3x lifespan."]),
    Turret("Hotdog",    "double the fun!",                            40, 0,  100,  "100/s",   "1s",    [(4, 4), (4, 4)],                 "Achieve victory in any mode with #B20$ different perks.", ["$Accuracy +50%$"],                                                                                                          ["Fires from both barrels at once."]),
    Turret("Avarice",   "SUPER...HOT...SUPER...HOT...",               10, 0,  50,   "25/s",    "0.5s",  [(4, 3), (4, 3), (4, 3)],         "Achieve victory in any mode at $Depth 5$ with #B30$ different turrets.", ["$Movespeed: 20$", "$Accuracy +70%$"],                                                                                       ["Time only moves when firing/aiming/moving."]),
    Turret("Inferno",   "set the depths ablaze.",                     40, 0,  100,  "100/s",   "1s",    [(4, 4)],                         "Achieve victory in any mode at $Depth 3 (or deeper)$ with a $Burn$ weapon that didn't originally have $Burn$.", ["$Burn$", "$Burn Damage +100%$"],                                                                                            ["$Microbes$ are only hurt by $Burn$."]),
    Turret("Tower",     "enemy spotted, dispatching.",                20, 0,  25,   "25/s",    "2s",    [(4, 3)],                         "Achieve victory in any mode at $Depth 5$ with #B20$ different weapons.", ["$Size +50%$"],                                                                                                              ["Every 5s, $Mark$ a random $Microbe$ and remove the $Mark$ from all others.", "When a $Marked$\n$Microbe$ is hit, it is eliminated and transfers the $Mark$ to a random\n$Microbe$ along with resetting the 5s timer.", "$HeatD$ is reduced by 1s when a\n$Microbe$ is eliminated. This resets on fire."]),
]