import random

def getFlavor():
    flavor = ""
    a = random.randint(1, 10)
    if(a == 1): flavor += "Chaos dances in jest."
    elif(a == 2): flavor += "Mirth amidst the madness."
    elif(a == 3): flavor += "The enigma's entertainer."
    elif(a == 4): flavor += "Madcap mischief in motion."
    elif(a == 5): flavor += "Madness under the big top."
    elif(a == 6): flavor += "Laughter laced with lunacy."
    elif(a == 7): flavor += "Cackling through the chaos."
    elif(a == 8): flavor += "Whimsy's wicked dance."
    elif(a == 9): flavor += "Juggling knives with a grin."
    elif(a == 10): flavor += "Malice and malcontent."
    return flavor

def getDescription():
    description = ""
    for i in range(5):
        b = random.randint(1, 290)
        if(b == 1): description += "<span style='color: #C040FF>Magic Resistance +70%</span>"
        elif(b == 2): description += "immune to <span style='color: #FF4040>Lava Damage</span>"
        elif(b == 3): description += "<span style='color: #40FF40>Jump Height +100%</span>"
        elif(b == 4): description += "gain <span style='color: #ff4040>Health</span> when <span style='color: #80FF80>Poisoned</span>"
        elif(b == 5): description += "<span style='color: #40ffcf>Knockback -150%</span>"
        elif(b == 6): description += "confuse <span style='color: #ff4070>microbes</span> when hit"
        elif(b == 7): description += "<span style='color: #40a0ff>Accuracy +101%</span>"
        elif(b == 8): description += "<span style='color: #cfff40>Turret Scale -30%</span> when you <span style='color: #40cfff>overheat</span>"
        elif(b == 9): description += "<span style='color: #40ff70>Movespeed +100%</span> at <span style='color: #4040ff>full Shield</span>"
        elif(b == 10): description += "<span style='color: #808080>Syndrome -5</span> after each wave"
        elif(b == 11): description += "<span style='color: #C080FF>Curses</span> reduce <span style='color: #ff4040>Health</span> by at most <span style='color: #ff4040>7</span>"
        elif(b == 12): description += "<span style='color: #FFC080>Reflect</span> always triggers twice"
        elif(b == 13): description += "<span style='color: #C0FF80>Sickness Duration +15s</span>"
        elif(b == 14): description += "<span style='color: #40DFFF>Freeze</span> <span style='color: #ff4070>demons</span> within <span style='color: #ffcf40>70% Range</span>"
        elif(b == 15): description += "<span style='color: #4040ff>Shield +0</span> every time you don't gain <span style='color: #4040ff>Shield</span>"
        elif(b == 16): description += "generate <span style='color: #4080FF>1 Sadness</span> every 3s"
        elif(b == 17): description += "projectiles form thriving civilizations beyond <span style='color: #ffcf40>50% Range</span>"
        elif(b == 18): description += "flying recharges energy weapons"
        elif(b == 19): description += "<span style='color: #40FFC0>Teleport</span> works on <span style='color: #40C080>Minions</span>"
        elif(b == 20): description += "reset cooldowns when <span style='color: #808040>Sludged</span>"
        elif(b == 21): description += "<span style='color: #C0C040>+180000 Extrusion Damage</span>"
        elif(b == 22): description += "weapons with <span style='color: #ff40ff>A DNA</span> are fun"
        elif(b == 23): description += "<span style='color: #ff4070>microbes</span> with <span style='color: #ffff40>T DNA</span> talk behind your back"
        elif(b == 24): description += "<span style='color: #40CFFF>Heat</span> no longer reduces <span style='color: #FFA040>Damage</span>"
        elif(b == 25): description += "<span style='color: #CFFF40>Size</span> and <span style='color: #FF8080>Sticky</span> are swapped"
        elif(b == 26): description += "<span style='color: #FFFF40>Biomass +300%</span>"
        elif(b == 27): description += "+0.6 Rerolls"
        elif(b == 28): description += "<span style='color: #ff4040>-1 Health</span> while at <span style='color: #ff4040>0 Health</span>"
        elif(b == 29): description += "<span style='color: #ffff40>Tax Fraud</span> occurs twice per wave"
        elif(b == 30): description += "<span style='color: #FFA040>Damage</span> reduces <span style='color: #ff4070>Microbe</span> <span style='color: #ff4040>Health</span> on hit"
        elif(b == 31): description += "<span style='color: #ff7040>Critical Hits</span> cause <span style='color: #ff7040>Critical Damage</span>"
        elif(b == 32): description += "<span style='color: #df8080>+666% Burn Damage</span>"
        elif(b == 33): description += "<span style='color: #ff40cf>Firerate</span> increases <span style='color: #00ffff>Pierce</span>"
        elif(b == 34): description += "card upgrades cost half <span style='color: #FFFF40>Biomass</span>"
        elif(b == 35): description += "<span style='color: #ffa0b8>offspring</span> generate <span style='color: #40cfff>Heat</span>"
        elif(b == 36): description += "<span style='color: #8080ff>Burst Fire +40%</span>"
        elif(b == 37): description += "every third item in the shop is itself"
        elif(b == 38): description += "the shop offers power-ups (<span style='color: #FFFF40>3 Biomass</span> each)"
        elif(b == 39): description += "unspent <span style='color: #FFC040>Grundo Tokens</span> are converted into snakes on the next turn"
        elif(b == 40): description += "choose up to 3 mutations every mutation alert"
        elif(b == 41): description += "<span style='color: #40cfff>Cooling Delay</span> scales with <span style='color: #40cfff>Cooling Delay</span>"
        elif(b == 42): description += "take quadruple damage"
        elif(b == 43): description += "<span style='color: #40ff70>Speed</span> increases are <span style='color: #40ff70>Speed</span> increases (and vice versa)"
        elif(b == 44): description += "ignore hits that miss you"
        elif(b == 45): description += "<span style='color: #bf80ff>Research +15%</span> after wave 450"
        elif(b == 46): description += "<span style='color: #a040ff>Murky Fog</span> is annoying"
        elif(b == 47): description += "<span style='color: #ff4070>microbes</span> eat sand regardless of <span style='color: #40a0ff>Accuracy</span>"
        elif(b == 48): description += "<span style='color: #BB2020>THE VOICES NEVER STOP</span>"
        elif(b == 49): description += "<span style='color: #FFFF20>BIG JUG HOT CHEESE</span>"
        elif(b == 50): description += "<span style='color: #FF20FF>HEE HEE HOO HOO HAA HAA</span>"
        elif(b == 51): description += "the Bookworm perk doesn't exist"
        elif(b == 52): description += "<span style='color: #ff7040>Critical Damage +1</span>"
        elif(b == 53): description += "<span style='color: #ff4070>microbes</span> impose their political views on you"
        elif(b == 54): description += "<span style='color: #ffff00>Homing +100%</span> to weapons with <span style='color: #ffff00>Homing +100%</span>"
        elif(b == 55): description += "<span style='color: #bf80ff>Research +0%</span>"
        elif(b == 56): description += "<span style='color: #40cfff>Cooling Delay +12345%</span>"
        elif(b == 57): description += "<span style='color: #ffa040>Damage -1000%</span>"
        elif(b == 58): description += "HONK :o)"
        elif(b == 59): description += "<span style='color: #df8080>Burn</span> <span style='color: #00ffff>Pierces</span> <span style='color: #ff8080>Sticky</span>-<span style='color: #95aaaa>Bounce</span>"
        elif(b == 60): description += "<span style='color: #40a0ff>Blue</span> is disabled"
        elif(b == 61): description += "<span style='color: #40ff70>Green -2</span>"
        elif(b == 62): description += "<span style='color: #ffcf40>Yellowish Orange +50%</span>"
        elif(b == 63): description += "<span style='color: #ff40cf>Firerate +30%</span> (only while you're alive)"
        elif(b == 64): description += "<span style='color: #202020>Dorcelessness +1</span>"
        elif(b == 65): description += "<span style='color: #ffff00>Explosion Duration +700%</span>"
        elif(b == 66): description += "<span style='color: #ff4070>Microbes</span> <span style='color: #00ffff>Pierce</span>"
        elif(b == 67): description += "<span style='color: #40ff70>Clouds are green</span>"
        elif(b == 68): description += "<span style='color: #95aaaa>Malice +400%</span>"
        elif(b == 69): description += "<span style='color: #ff8080>Chaos +35%</span>"
        elif(b == 70): description += "<span style='color: #40ffcf>Disaster +20%</span>"
        elif(b == 71): description += "<span style='color: #ff40cf>Medical Damage +50%</span>"
        elif(b == 72): description += "<span style='color: #ff7040>Critical Chance +1/3</span>"
        elif(b == 73): description += "Projectiles +3000% (<span style='color: #FF4040>WARNING: HUGE PERFORMANCE IMPACT!</span>)"
        elif(b == 74): description += "<span style='color: #cfff40>Size +15%</span>"
        elif(b == 75): description += "<span style='color: #ff7040>Critical Chance +200%</span>"
        elif(b == 76): description += "<span style='color: #ffcf40>Range +60%</span>"
        elif(b == 77): description += "<span style='color: #ff8080>Sticky</span>"
        elif(b == 78): description += "<span style='color: #ff40cf>Firerate -200%</span>"
        elif(b == 79): description += "Oversized <span style='color: #ff4070>Microbe</span> Chance +999%"
        elif(b == 80): description += "<span style='color: #40ff70>Speed +5%</span>"
        elif(b == 81): description += "<span style='color: #FF0000>Clown Disease +100%</span>"
        elif(b == 82): description += "projectiles see you as their god"
        elif(b == 83): description += "nobody likes you"
        elif(b == 84): description += "<span style='color: #a040ff>Mucus Membrane +7</span>"
        elif(b == 85): description += "<span style='color: #df4080>Hyper Mode +300%</span>"
        elif(b == 86): description += "all stats are 1"
        elif(b == 87): description += "immune to buffs"
        elif(b == 88): description += "<span style='color: #ff40cf>Candy</span> lowers <span style='color: #ff2020>Blood Pressure</span>"
        elif(b == 89): description += "illness"
        elif(b == 90): description += "you're afraid of mirrors"
        elif(b == 91): description += "<span style='color: #40ff70>Carnival Duration +10s</span>"
        elif(b == 92): description += "the king thinks you're funny"
        elif(b == 93): description += "<span style='color: #bf80ff>Research +1500%</span>"
        elif(b == 94): description += "<span style='color: #ffff00>Springs</span> hit all <span style='color: #ff4070>microbes</span>"
        elif(b == 95): description += "<span style='color: #8080ff>Strange Purple Liquid</span>"
        elif(b == 96): description += "items in the shop cost <span style='color: #DDFF40>real-world money</span>"
        elif(b == 97): description += "<span style='color: #FFFF30>THIS TURRET IS <u>PAID DLC</u></span>"
        elif(b == 98): description += "<span style='color: #40cfff>cheating</span> is disabled"
        elif(b == 99): description += "<span style='color: #00ffff>Pierce</span> just kinda doesn't work"
        elif(b == 100): description += "<span style='color: #40C080>People</span> want to kill you"
        elif(b == 101): description += "the <span style='color: #a040ff>Thwarps</span> know your location"
        elif(b == 102): description += "<span style='color: #AA7040>Sickness Eyes</span>"
        elif(b == 103): description += "<span style='color: #95aaDD>Broken Leg x40</span>"
        elif(b == 104): description += "<span style='color: #FFDD80>Chicken Nacho Supreme</span>"
        elif(b == 105): description += "the blood never goes away no matter how much you wash your hands"
        elif(b == 106): description += "<span style='color: #BFDFFF>Doors</span> are now <span style='color: #FFE7BF>Windows</span>"
        elif(b == 107): description += "<span style='color: #ffff00>Homing -100%</span>"
        elif(b == 108): description += "<span style='color: #df8080>Burn Damage</span> hurts"
        elif(b == 109): description += "<span style='color: #ffcf40>Range</span> and <span style='color: #ffcf40>Range</span> are swapped"
        elif(b == 110): description += "<span style='color: #4040ff>Shield</span> now causes diseases"
        elif(b == 111): description += "<span style='color: #ffcfff>MANY sliced apples</span>"
        elif(b == 112): description += "<span style='color: #4080ff>glowing blue lights</span> assault your retinas"
        elif(b == 113): description += "<span style='color: #8040ff>what`s</span>"
        elif(b == 114): description += "entering <span style='color: #ff40ff>denizens</span> immediately upgrades <span style='color: #FF4040>Sticky Note</span>"
        elif(b == 115): description += "<span style='color: #ff8040>Fuzzy</span> <span style='color: #808080>Metalbigironpipes</span> are the key"
        elif(b == 116): description += "the pause menu is disabled"
        elif(b == 117): description += "what if there was a horse (named Bill):that was named John"
        elif(b == 118): description += "man I dunno"
        elif(b == 119): description += "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        elif(b == 120): description += "the letter 7 is infected with <span style='color: #ff4040>Yellow</span>"
        elif(b == 121): description += "<span style='color: #ff40cf>Firerate</span> is objectively better than <span style='color: #ffa040>Damage</span>"
        elif(b == 122): description += "you forget what the <span style='color: #80FFFF>weather</span> isn't"
        elif(b == 123): description += "Rerolls -100"
        elif(b == 124): description += "<span style='color: #DDFF80>Party Rock</span> is in the house tonight"
        elif(b == 125): description += "<span style='color: #cfff40>Size +50%</span> to lonely projectiles"
        elif(b == 126): description += "<span style='color: #40ff70>30 Movespeed (WASD/LStick)</span>, shred <span style='color: #ff4070>microbes</span> for <span style='color: #40cfff>Fuel</span> (more if oversized):and +5s of <span style='color: #40ff70>+30% Movespeed</span> & <span style='color: #ff40cf>+30% Firerate</span> & <span style='color: #40ff70>+30% Speed</span> (max 5 stacks), destroyed when <span style='color: #40cfff>out of Fuel</span>, <span style='color: #ff4040>Health</span> is reduced by at most <span style='color: #ff4040>1</span> when hit, <span style='color: #40a0ff>360° Accuracy</span>"
        elif(b == 127): description += "<span style='color: #40FFC0>Bro</span> is drippin"
        elif(b == 128): description += "Windows users are forced to switch to Mac and vice versa"
        elif(b == 129): description += "<span style='color: #ff4040>Health Situation</span>"
        elif(b == 130): description += "<span style='color: #ff4040>+2 Health</span> when wait actually nvm"
        elif(b == 131): description += "<span style='color: #FF4040><b>object reference not set to an instance of an object</b></span>"
        elif(b == 132): description += "<size=300%><span style='color: #FF0000>LARGE</span></size>"
        elif(b == 133): description += "Jason is your only true friend"
        elif(b == 134): description += "<span style='color: #80FFC0>+3 Normal Maps</span>"
        elif(b == 135): description += "you instantly die if it's <span style='color: #ffff80>Sunday</span>"
        elif(b == 136): description += "<span style='color: #40ff70>Speed +90%</span> to YouTubers with 300k+ subscribers"
        elif(b == 137): description += "<span style='color: #ff40cf>Firerate</span> is now <span style='color: #40a0ff>Fish</span>"
        elif(b == 138): description += "<span style='color: #0000FF>glowy light orbs</span>"
        elif(b == 139): description += "<span style='color: #a040ff>The Abyss</span> comes back to life"
        elif(b == 140): description += "cosmetics apply stat bonuses"
        elif(b == 141): description += "<span style='color: #bf80ff>Research</span> becomes pointless after a while"
        elif(b == 142): description += "the thing before this is actually true"
        elif(b == 143): description += "generate a stack of <span style='color: #FFAA40>Cheese</span> during the effects of <span style='color: #80FF40>Sandwich Mania</span>"
        elif(b == 144): description += "<span style='color: #FF4040>APDQ6-2BI86-FHIRX (too late pal, it got redeemed)</span>"
        elif(b == 145): description += "<span style='color: #8080FF>Highscores</span> reset upon destruction"
        elif(b == 146): description += "<span style='color: #4040ff>Shield</span> prevents <span style='color: #ffcf40>Range</span> reduction"
        elif(b == 147): description += "defeat <span style='color: #FF4040>VAC bans</span> your Steam account (itch.io users will simply be killed instead)"
        elif(b == 148): description += "some guy named <span style='color: #FFAA00>Desmond</span> is at the door irl"
        elif(b == 149): description += "permanent <span style='color: #ffa040>-20% Damage</span> to all turrets if you don't achieve victory with Jester within the next 30 minutes"
        elif(b == 150): description += "<span style='color: #AAAAAA>bro is laughing</span>"
        elif(b == 151): description += "<span style='color: #FF4040><b>you must construct additional pylons</b></span>"
        elif(b == 152): description += "randomness that straight up kills you is <span style='color: #FF8040>wholly unfun</span>"
        elif(b == 153): description += "lying in <span style='color: #60cfff>Puddles</span> makes you <span style='color: #60cfff>Sad</span> & <span style='color: #60cfff>Alone</span>"
        elif(b == 154): description += "all <span style='color: #FF2020>Lies</span> are <span style='color: #20FF20>Truths</span>"
        elif(b == 155): description += "<span style='color: #FF8080>I'M TRAPPED INSIDE A DESCRIPTION OH GOD HELP</span>"
        elif(b == 156): description += "<span style='color: #FF3030><u>(You)</u></span> need to get it together"
        elif(b == 157): description += "Power-ups seek answers"
        elif(b == 158): description += "<span style='color: #ffa040>Damage</span> scales with <span style='color: #ffa040>HTML tags</span>"
        elif(b == 159): description += "<span style='color: #DDFF80>Firerate</span> uses the wrong colour"
        elif(b == 160): description += "<span style='color: #40ff70>Speed</span> isn't a very useful stat"
        elif(b == 161): description += "<span style='color: #ff4070>microbes</span> steal yo girl"
        elif(b == 162): description += "the Shuriken turret is busted"
        elif(b == 163): description += "<span style='color: #40DD40>free MONAAAAAAAAAY ahaaah</span>"
        elif(b == 164): description += "you are the proud owner of <span style='color: #eb5e34>www.chickenupload.com</span>"
        elif(b == 165): description += "<span style='color: #732a06>Drinko-ultra Mode</span>"
        elif(b == 166): description += "<span style='color: #40FFCF>Knockback</span> becomes a desirable stat"
        elif(b == 167): description += "<span style='color: #cfff40>Size</span> matters"
        elif(b == 168): description += "<span style='color: #cfcc2d>Bickory Sticks lmao</span>"
        elif(b == 169): description += "<span style='color: #40cfff>Heat Max +5%</span>, <span style='color: #40cfff>Heat Max +5%</span>, <span style='color: #40cfff>Heat Max +5%</span>, <span style='color: #40cfff>Heat Max +5%</span>, <span style='color: #40cfff>Heat Max +5%</span>, <span style='color: #40cfff>Heat Max +5%</span>, <span style='color: #40cfff>Heat Max +5%</span>, <span style='color: #40cfff>Heat Max +5%</span>, <span style='color: #40cfff>Heat Max +5%</span>"
        elif(b == 170): description += "there's something kinda <span style='color: #b03ec7>off</span> about this turret but you can't put your finger on what"
        elif(b == 171): description += "80% chance to ignore hits while at or below <span style='color: #ff4040><b>SYKE YOU GET NOTHING</b></span>"
        elif(b == 172): description += "<span style='color: #ffa0b8>Offspring</span> now refers to the band"
        elif(b == 173): description += "<span style='color: #8080ff>Burst Fire</span> weapons fire in -5 shot bursts"
        elif(b == 174): description += "<span style='color: #95aaaa>Bounce</span> actually makes <span style='color: #00FFFF>Hitscan</span> shots bounce"
        elif(b == 175): description += "the <span style='color: #a040ff>Thwarps</span> are closing in"
        elif(b == 176): description += "the <span style='color: #a040ff>Thwarps</span> have been misdirected"
        elif(b == 177): description += "the intro cutscene plays again"
        elif(b == 178): description += "<span style='color: #ffa040>Damage +30%</span> to the CREDITS menu"
        elif(b == 179): description += "someone named <span style='color: #4dfac9>Fresno</span> called (they left a message)"
        elif(b == 180): description += "Power-ups want to show you a <span style='color: #fe0000>YouTube</span> video on their phone"
        elif(b == 181): description += "you lap milk up like like um like dude like um"
        elif(b == 182): description += "you think \"<span style='color: #f7a71b>Cheeto Mario</span>\" is funny (reason unknown)"
        elif(b == 183): description += "you're a full-grown adult that confuses \"your\" and \"you're\""
        elif(b == 184): description += "<span style='color: #40ffff>C DNA</span> ruin your life"
        elif(b == 185): description += "<span style='color: #4040ff>Shield Max</span>"
        elif(b == 186): description += "Wave Time -200%"
        elif(b == 187): description += "+10% chance of <span style='color: #ff7040>Critical Chance +5%</span> per elimination"
        elif(b == 188): description += "a link to a good deal on <span style='color: #ffcf40>Gumber's Quest 64</span> (with box + manual):opens when you achieve victory"
        elif(b == 189): description += "+30% chance that <span style='color: #ff4070>microbes</span> forget to wash their hands after using the bathroom"
        elif(b == 190): description += "<span style='color: #40cfff>-50% Heat Increase</span> while eating <span style='color: #40cfff>buncha ice cubes yo what</span>"
        elif(b == 191): description += "<span style='color: #ff4070>microbes</span> stop moving "
        elif(b == 192): description += "you forget what <span style='color: #ffa0b8>Offspring</span> means every 3 waves"
        elif(b == 193): description += "<span style='color: #a040ff>Abyssian Hunters</span> eat your hair (ironically)"
        elif(b == 194): description += "all weapons have <span style='color: #FF8020>Four-Wheel Drive</span>"
        elif(b == 195): description += "<span style='color: #ff4040>Health</span> gains during a wave decrease <span style='color: #ff4040>Health</span> instead"
        elif(b == 196): description += "your suggestions in the <span style='color: #5865f2>Discord</span> are ignored"
        elif(b == 197): description += "<span style='color: #40cfff>Fooling Rate +100%</span>"
        elif(b == 198): description += "<span style='color: #40cfff>Cooling Delay -40%</span>, <span style='color: #40cfff>Cooling Delay +40%</span>"
        elif(b == 199): description += "<span style='color: #40cfff>overeating</span> makes you fat"
        elif(b == 200): description += "<span style='color: #40ff70>30 Movespeed (ESDF/RStick)</span>"
        elif(b == 201): description += "<span style='color: #ff4058>Alpherior</span> is glad you're playing his game but disappointed with how bad you are at it"
        elif(b == 202): description += "<span style='color: #5e84f4>The Government</span> wants to come over for a sleepover"
        elif(b == 203): description += "getting hit by an <span style='color: #ffa0b8>offspring</span> eliminates <span style='color: #d9d084>Gwimbly</span>"
        elif(b == 204): description += "defeat is now more like <span style='color: #FF3020>duh feet</span>"
        elif(b == 205): description += "<span style='color: #dfff00>Area Radius +51%</span>"
        elif(b == 206): description += "all power-ups aren't <span style='color: #ff40cf>TRIPLE FIRERATE</span>"
        elif(b == 207): description += "<span style='color: #2ba0ff>Zoomers</span> are <span style='color: #33bf1b>Boomers</span> and vice versa"
        elif(b == 208): description += "<span style='color: #40ffff>CCC</span><span style='color: #FFFF40>T</span> Tracking Laser finally gets nerfed <span style='color: #4af9ff>(side-effect: your day is ruined)</span>"
        elif(b == 209): description += "this turret annoyed someone so much that they uninstalled"
        elif(b == 210): description += "<span style='color: #ff4040>Healf</span> is dos increase bigg"
        elif(b == 211): description += "<span style='color: #ff7040>Critical Damage</span>... uh... actually no, scrap that"
        elif(b == 212): description += "all stats stack <span style='color: #FF8080>additively</span>"
        elif(b == 213): description += "your fetish becomes <span style='color: #131414>lump a coal</span> upon defeat"
        elif(b == 214): description += "you've got moves like <span style='color: #c926ff>Dordin Bristol</span>"
        elif(b == 215): description += "some <span style='color: #ff40cf>Pink Thing</span>"
        elif(b == 216): description += "+18% to Quality"
        elif(b == 217): description += "all <span style='color: #e8c76d>Physical Damage</span> is converted to <span style='color: #4174f2>Magic Damage</span>"
        elif(b == 218): description += "the <span style='color: #4368c4>Council of Wizards</span> is rooting for you"
        elif(b == 219): description += "brand-name toothpaste no longer gives you a <span style='color: #cc7454>Headache</span>"
        elif(b == 220): description += "legal ownership of <span style='color: #e6ff29>Expired Pinto Beans</span> is passed on to you up to 5000 times per wave"
        elif(b == 221): description += "you really just don't know anymore"
        elif(b == 222): description += "<span style='color: #54d2e8>Crazy Frogs</span> are just <span style='color: #37ad31>Frogs</span> to you"
        elif(b == 223): description += "you're eating the <span style='color: #FFDD50>Mac & Cheese</span> you made"
        elif(b == 224): description += "you want to make <span style='color: #FFDD50>Mac & Cheese</span>"
        elif(b == 225): description += "you are a \"<span style='color: #e8cf84>Fun gi</span>\" <span style='color: #FF4040>(<b>warning:</b> timeless mushroom humour)</span>"
        elif(b == 226): description += "+ a whole lotta <i>SOMETHIN'</i> I tell ya HWAT"
        elif(b == 227): description += "immune to <span style='color: #575757></span> & <span style='color: #f2e24e>Lamp Oil</span> & <span style='color: #ffe605>Bombs</span>"
        elif(b == 228): description += "you have to endure being <span style='color: #69a5ff>British</span> after wave 20"
        elif(b == 229): description += "<span style='color: #005bed>Everything</span> <span style='color: #e61c41>Upsets</span> you"
        elif(b == 230): description += "walking the dog eliminates <span style='color: #ff4070>microbes</span>"
        elif(b == 231): description += "bro is goin thru a <b><span style='color: #0d0d0d>Dark Ages</span></b>"
        elif(b == 232): description += "<span style='color: #d60000>Analog Horror</span> is now <span style='color: #575dcf>Digital Horror</span>"
        elif(b == 233): description += "immune to <span style='color: #52dfff>Darrell's Wrath</span>"
        elif(b == 234): description += "turret destruction reverts your game version back to X.X.X"
        elif(b == 235): description += "<span style='color: #40cfff>overheating</span> softlocks the game"
        elif(b == 236): description += "<span style='color: #ffff00>Explosive Damage</span> extends to hit <span style='color: #ff4070>microbes'</span> loved ones"
        elif(b == 237): description += "+10% chance <span style='color: #ff4070>microbes</span> doxx you"
        elif(b == 238): description += "<span style='color: #ff9a36>Pizza Time</span> (this is wildly inaccurate)"
        elif(b == 239): description += "defeat removes <span style='color: #aoff40>GGGG</span> Wavequake from the game"
        elif(b == 240): description += "<span style='color: #00ffb3>Voting Rights</span> now scales with <span style='color: #40a0ff>Accuracy</span>"
        elif(b == 241): description += "<span style='color: #40a0ff>Accuracy</span> scales with remaining Rerolls"
        elif(b == 242): description += "<span style='color: #bf80ff>Research</span> and <span style='color: #FFFF40>Biomass</span> are swapped"
        elif(b == 243): description += "<span style='color: #FFFF40>Biomass</span> looks kinda like a fidget spinner"
        elif(b == 244): description += "<span style='color: #FF0080>Opinions</span> melt <span style='color: #ff4070>microbe</span> flesh"
        elif(b == 245): description += "you really DO know what they say about assuming"
        elif(b == 246): description += "<span style='color: #22ff00>VERY GREEN oo ye supe vry green rly good</span>"
        elif(b == 247): description += "use up to <span style='color: #AA8060>6 Argumentative Fallacies</span> per wave without consequence"
        elif(b == 248): description += "<span style='color: #ff4d00>a nice shade of orange</span> graces your screen with its presence"
        elif(b == 249): description += "<span style='color: #FFFF40>The King</span> regrets his choice of entertainment"
        elif(b == 250): description += "<span style='color: #FFDD40>Distance -70%</span> (from what, you're not sure)"
        elif(b == 251): description += "<span style='color: #FF6040>Gambling Addition +777</span>"
        elif(b == 252): description += "You look like the dude from the thing"
        elif(b == 253): description += "you're making <span style='color: #FFDD50>Mac & Cheese</span>"
        elif(b == 254): description += "you're <span style='color: #8368BA>Haunted</span> by the <span style='color: #8368BA>Ghost of Chobungus</span>"
        elif(b == 255): description += "you remember that your jaw has weight"
        elif(b == 256): description += "<span style='color: #FF6060>Epic Trololo</span> <span style='color: #ff4070>microbes</span> on hit"
        elif(b == 257): description += "<span style='color: #8090FF>Executive Mode</span> fires twice as many <span style='color: #ff4070>employees</span>"
        elif(b == 258): description += "<span style='color: #40FFF2>+300% Viewers</span>"
        elif(b == 259): description += "<span style='color: #808080>Endless Mutations</span> now eventually end"
        elif(b == 260): description += "famous actor <span style='color: #FF8070>Cheddy Broger</span> respects you"
        elif(b == 261): description += "Invisible squiggly projectiles & <span style='color: #ffff00>Explosions</span> that aim backwards have no <span style='color: #ffa0b8>offspring</span>"
        elif(b == 262): description += "<span style='color: #5050ff>Responsible -999999999%</span>"
        elif(b == 263): description += "<span style='color: #a040ff>Plaid Power-ups</span> astound you with style"
        elif(b == 264): description += "<span style='color: #40cfff>overheat</span> while at <span style='color: #40cfff>100% Heat</span>"
        elif(b == 265): description += "instantly <span style='color: #40ffcf>Ploob</span> (no warning)"
        elif(b == 266): description += "<span style='color: #00ffff>Pierce</span> is now <span style='color: #00ffff>Fierce</span>"
        elif(b == 267): description += "you love the taste of <span style='color: #806000>Disease-flavoured Gum</span>"
        elif(b == 268): description += "someone said \"this game should not require <span style='color: #FFFF40>mindless manual aiming</span>\" in a review"
        elif(b == 269): description += "<span style='color: #EE9030>Dog Big</span>"
        elif(b == 270): description += "<span style='color: #6060FF>Jokes</span> are cast instantly upon <span style='color: #60FF60>Blokes</span>"
        elif(b == 271): description += "<span style='color: #74B5A9>+603,782,103,772,451 Sardines</span>"
        elif(b == 272): description += "Pretzel firing pattern"
        elif(b == 273): description += "<span style='color: #ffa040>-100% Damage</span> if you read this out loud"
        elif(b == 274): description += "<span style='color: #697254>Mouth Crickets</span>"
        elif(b == 275): description += "<span style='color: #FF4040>Cringe</span> is now <span style='color: #40FF60>Based</span> and vice versa"
        elif(b == 276): description += "<span style='color: #FFFF25>Nuclear Trans-armament Volatile Fixed-point Detonation</span>"
        elif(b == 277): description += "<span style='color: #ff4070>microbes</span> with <span style='color: #ff40ff>A DNA</span> are magenta (not \"red\" or \"purple\")"
        elif(b == 278): description += "+30% Riceballllllllllllllllll"
        elif(b == 279): description += "Arachnophobia Mode is disabled"
        elif(b == 280): description += "victory grants you immunity from being <span style='color: #FF2020>Cancelled</span> 1 time"
        elif(b == 281): description += "<span style='color: #c5de73>seeds</span>"
        elif(b == 282): description += "<size=150%><span style='color: #FF4530><b>WEEF BELLINGTON MODE ENGAGED</b></span></size>"
        elif(b == 283): description += "<span style='color: #827F6D>17 Wild Hogs</span> are at your door"
        elif(b == 284): description += "this turret makes unlocking the Amber perk much easier"
        elif(b == 285): description += "get a Steam key for <span style='color: #F5FE73>\"Horse Disease\"</span> upon victory"
        elif(b == 286): description += "<span style='color: #ff7040>Critical Damage +100%</span> each time you write a short story about a muffin"
        elif(b == 287): description += "<span style='color: #0080FF>genomeguardian.threadless.com/</span>"
        elif(b == 288): description += "you absolutely don't give a <span style='color: #B8B826>rat's uncle</span> anymore"
        elif(b == 289): description += "you can't do anything"
        elif(b == 290): description += "<span style='color: #FF1060>Schlumbus</span> is now possible"

        if(i != 4): description += ", "
    return description